version: '3.8'

services:
  PeopleFlow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peopleflow
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - peopleflow_uploads:/app/uploads
    environment:
      - GIN_MODE=release
      - TZ=Europe/Berlin
      - MONGODB_URI=mongodb://mongodb:27017/peopleflow
    depends_on:
      - mongodb
    networks:
      - peopleflow-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - peopleflow-network

networks:
  PeopleFlow-network:
    driver: bridge

volumes:
  mongodb_data:
  PeopleFlow_uploads: